check_availability: true

filters:
  districts:
    - "黄浦区"
    - "静安区"
    - "长宁区"
    - "普陀区"
    - "杨浦区"
  only_stations:
    - "汉庭优佳上海中山公园延安西路酒店"
    - "7天酒店（上海江宁路地铁站玉佛寺）"
    - "汉庭上海静安寺江宁路新酒店"
    - "友间公寓大统路社区"
    - "7天酒店（新7天上海西藏南路地铁站）"
    - "卢宛158项目"
    - "微领地新静安中心社区（二期）"
    - "白玉兰酒店大宁国际同济医院"
    - "和欣公寓"
    - "汉庭上海五角场酒店"
  name: ""
  apply_scope: "personal"
  date_from: "2026-10-08"
  date_to: "2026-10-18"
  min_apply_number: 1
  min_house_count: 0

notify:
  type: "bark"
  url: "https://api.day.app/NLo5BweUp9QYWTCerNRYnN"
