check_availability: true

filters:
  districts:
    - "黄浦区"
    - "静安区"
    - "长宁区"
    - "虹口区"
    - "普陀区"
    - "杨浦区"
  only_stations: []
  name: ""
  apply_scope: "personal"
  date_from: "2026-10-08"
  date_to: "2026-10-15"
  min_apply_number: 1
  min_house_count: 0

notify:
  type: "bark"
  url: "https://api.day.app/NLo5BweUp9QYWTCerNRYnN"
